# Modules
# In python, we can put code into different files and import that code if needed. This means that we can better organise and modularise our code.
# You can create a new module simply by creating a new .py file, and then you can import variables or functions from that file just by using the import keyword.
# for e.g. you created a file called mymodule.py and defined a variable myvar = 10
# Now, in the file you are coding, you can import mymodule
# and use var as, print(mymodule.myvar)

# To use Random Module you need to first import it:
# import random

#Random Whole Numbers Within a Range
import random
rand_num = random.randint(1, 10)
#This will produce a random whole number between 1 and 10 (inclusive).


#Random Floats
import random
rand_float = random.random()
# It can also be represented like this- 0.0 <= random.random() < 1.0
# You can expand the range of random numbers generated by this method using multiplication.
random.random() * 5
# Multiplying by 5 expands this range to [0.0,5.0)
# Here's how:
# Minimum value: 0.0 × 5 = 0.0
# Maximum value: 1.0 × 5 = 5.0 (exclusive).
# Thus, random.random() * 5 generates random numbers between 0 (inclusive) and 5 (exclusive).

#Alternative to expanding random()
rand_f = random.uniform(1,10)
#This will generate a random floating point number between 1 and 10.
# This method may or may not include the upper bound depending on the rounding of the floating point number. So it's best represented as:
# a <= random.uniform(a,b) <= b

#Create a coin flip program using what you have learnt about randomisation in Python. It should randomly print "Heads" or "Tails" everytime it is run.
random_num = random.randint(0,1)
if random_num == 0:
    print("Heads")
else:
    print("Tails")